const ApiUrl = {
    LOGIN: 'auth/login',
    SEND_OTP: 'auth/validate-otp',
    SIGNUP_1: 'customer/',
    SIGNUP_2: '/profile-update',
    LOG_OUT: 'auth/logout',
    store:'store/store/',
    store_card:'store/store-card-list',
    store_addcart:'store/addcart-details',
    store_category:'store/category?store=',
    Sub_category:'store/sub-category?store=',
    StoreFav:'store/store-favirote-list',
    like:'store/like-store',
    store_card_create:'store/store-card-create',
    store_card_details:'store/store-card-details/',
    store_card_edit:'store/store-card-edit/update/',
    store_like_Product:'store/like-Product',
    store_Product_search:'store/Product-search?search=',
    product_detail:'store/product-detail/',
    shoppinglist_item_create:'store/shoppinglist-item-create',
    shoppinglist_item_details:'store/shoppinglist-item-details',
    store_Itemlist_update:'store/itemlist-update/',
    shoppinglist_item_delete:'store/shoppinglist-item_delete/',
    shoppinglist_item:'store/shoppinglist-item/',
    store_Product_search:'store/Product-search',
    CONTACT_SYNC: 'customer/contact/sync',
    CONTACT_SYNC_LIST :'customer/contact/sync_list',
    Invitation:'customer/invitation/send/',
    Subscription:'customer/subscription-plan-list/',
    Add_connection:'customer/add-connection/',
    GetFamilyList:'customer/invitation/list/family/',
    GetneighbourList:'customer/invitation/list/neighbour/',
    deleteFamilylist:'customer/invitions/family-member-remove/',
    updateAdmin:'customer/invitation/status-update/',
    neighbourList:'customer/get-connected-neighbour?',
    SendRequest:'customer/get-connected-neighbour-send-notify',
    get_connectedNeighbour:'customer/get-connected-neighbour-sharelist',
    get_productbyOrder:'store/Product-orderby',
    addPlanApi:'customer/subscription-plan-add',
    getNotification:'customer/get-connected-neighbour-notification-list',
    notifyStatus:'customer/invitation/status-update/',
    AddCartDelete:'store/addcart-delete/',
    AddToCart:"store/addcart",
    replaceData:"store/substitute-shoppinglist-item-replace?Itemlistid=",
    replaceAdd:"store/substitute-item-add-itemlist",
    inviteSend:"customer/invitation/send/",
    getBanner:"customer/users-banner-api"
}
export default ApiUrl