require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'KarkKick' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
 
   pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera/Permission-Camera.podspec"
   
   pod 'Permission-PhotoLibrary', :path => "../node_modules/react-native-permissions/ios/PhotoLibrary/Permission-PhotoLibrary.podspec"

   # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
   # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  #target 'KarkKickTests' do
   # inherit! :complete
    # Pods for testing
  #end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
   # flipper_post_install(installer)
  #end

end

#target 'KarkKick-tvOS' do
  # Pods for KarkKick-tvOS

#  target 'KarkKick-tvOSTests' do
 #   inherit! :search_paths
    # Pods for testing
  #end
#end
